import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/react';
import { Toaster } from "sonner";

import "./globals.css";
import '../assets/css/quick-styles.css';
import '../assets/css/app.css';

import Header from '../ui/Header/Header';
import SiteOverview from "../ui/SiteOverview/SiteOverview";
import Footer from "../ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" />
        <Header version={1.59} setVersion={() => {}} />
        <main className="flex">
          <SiteOverview version={1.59} />
          <main className="flex fd-column width100per">
            {children}
            <Footer />
          </main>
        </main>
        <Analytics />
      </body>
    </html>
  );
}
