name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=trailing-whitespace,trailing-newlines,unused-import,import-outside-toplevel,possibly-used-before-assignment,missing-module-docstring,broad-exception-caught,import-error,too-many-locals,inconsistent-return-statements,unspecified-encoding,too-few-public-methods,duplicate-code $(git ls-files '*.py')
